services:
  solace:
    image: solace/solace-pubsub-standard:latest
    container_name: solace
    hostname: solace
    shm_size: '1g'  # Added this back - Solace often fails to boot without it
    ulimits:
      core: -1
      nofile:
        soft: 2448
        hard: 1048576
    environment:
      - ACCEPT_EULA=yes
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
    ports:
      - "8081:8080"   # Admin Console
      - "55556:55555" # Spring Boot SMF
      - "9000:9000"   # REST
      - "8008:8008"   # Web socket
    volumes:
      # Use the absolute or relative path to your local folder
      - ../../.ignore/solace/solace_data:/var/lib/solace
    networks:
#      - solace-net
      - traefik-net
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.solace.rule=Host(`solace.homelabs.suriyaprakhash.com`)"
      - "traefik.http.routers.solace.entrypoints=web"
      - "traefik.http.services.solace.loadbalancer.server.port=8080"

networks:
#  solace-net:
#    driver: bridge
  traefik-net:
    external: true