services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - /Users/suriya/main/ws/github/docker-collection/.ignore/mysql/mysql_db_data:/var/lib/mysql