services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    networks:
      - prometheus-network

networks:
  prometheus-network:

volumes:
  prometheus_data: